const gameConfig = {
  characters: [ //SEPARATED BY ELEMENT
    
    //PYRO 
    { name: 'Amber', imgName: 'Ambor', have: [true], 
        spriteImages: ['Warm_Greeting'] },
    { name: 'Bennett', have: [false], 
        spriteImages: ['Filled_With_Confidence','Upbeat_Encouragement'] },
    { name: 'Hu Tao', spriteFolder: 'HuTao', have: [false], 
        spriteImages: ['Leisurely_Moment'] },
    { name: 'Gaming', have: [true], 
        spriteImages: ['Perfect_Partner'] },
    { name: 'Klee', have: [true, false], 
        spriteImages: ['Happy_Times', 'Bombonanza'] },
    { name: 'Lyney', imgName: 'Liney', have: [true], 
        spriteImages: ['Elegant_Greeting'] },
    { name: 'Thoma', imgName: 'Tohma', have: [false], 
        spriteImages: ['Leisure_Time'] },
    { name: 'Xiangling', have: [true], 
        spriteImages: ['Upbeat_Encouragement'] },
    { name: 'Yoimiya', have: [true], 
        spriteImages: ['Filled_With_Confidence'] },
    { name: 'Diluc', have: [false], 
        spriteImages: ['All_Green_and_Good_to_Go'] },
    { name: 'Xinyan', have: [false], 
        spriteImages: ['Performance_Time'] },
    { name: 'Yanfei', have: [false], imgName: 'Feiyan',
        spriteImages: ['Case_Overview'] },

    //HYDRO
     { name: 'Ayato', have: [false], 
        spriteImages: ['Solemn_Countenance'] },
    { name: 'Barbara', have: [true], 
        spriteImages: ['Upbeat_Encouragement'] },
    { name: 'Candace', have: [false], 
        spriteImages: ['Ready_for_Battle'] },
    { name: 'Kokomi', have: [false], 
        spriteImages: ['Leisure_Time_Sangonomiya'] },
    { name: 'Mona', have: [false], 
        spriteImages: ['Elegant_Countenance'] },
    { name: 'Mualani', have: [true], 
        spriteImages: ['Puffy_Polka'] },
    { name: 'Neuvillette', have: [true], 
        spriteImages: ['Leisure_Time'] },
    { name: 'Tartaglia', have: [true], 
        spriteImages: ['All_Green_and_Good_to_Go'] },
    { name: 'Yelan', have: [false], 
        spriteImages: ['Elegant_Countenance','Leisure_Time'] },
    { name: 'Xingqiu', have: [false], 
        spriteImages: ['Leisurely_Moment'] },
    { name: 'Furina', have: [true], 
        spriteImages: ['Tea_Time'] },
        
    //DENDRO
    { name: 'Alhaitham', imgName: 'Alhatham', have: [false], 
        spriteImages: ['Noise_Filtering', 'Reading_Time'] },
    { name: 'Baizhu', imgName: 'Baizhuer', have: [false], 
        spriteImages: ['Leisure_Time'] },
    { name: 'Collei', have: [true, false], 
        spriteImages: ['Looking_Around_Curiously', 'Deep_Contemplation'] },
    { name: 'Nahida', have: [true], 
        spriteImages: ['Sharp_Observer'] },
    { name: 'Kinich', have: [true], 
        spriteImages: ['Battle_Preparation'] },
    { name: 'Kaveh', have: [true], 
        spriteImages: ['Careful_Negotiations'] },
    { name: 'Tighnari', have: [false], 
        spriteImages: ['Deep_Contemplation'] },
    { name: 'Yaoyao', have: [false], 
        spriteImages: ['Cheerful_Greeting'] },

    //ELECTRO
    { name: 'Beidou', have: [false], 
        spriteImages: ['Gathered_Over_Drinks'] },
    { name: 'Dori', have: [false], 
        spriteImages: ['Merchant\'s_Aura'] },
    { name: 'Cyno', have: [false], 
        spriteImages: ['Ready_for_Battle'] },
    { name: 'Fischl', have: [false], 
        spriteImages: ['Prinzessins_Majesty', 'Refined_Countenance'] },
    { name: 'Keqing', have: [false], 
        spriteImages: ['Ready_for_Battle'] },
    { name: 'Lisa', have: [false], 
        spriteImages: ['Leisure_Time'] },
    { name: 'Raiden Shogun', imgName: 'Shougun', spriteFolder: 'Raiden', have: [true], 
        spriteImages: ['Ready_for_Battle'] },
    { name: 'Razor', have: [false], 
        spriteImages: ['Watching_and_Waiting', 'All_Green_and_Good_to_Go'] },
    { name: 'Sethos', have: [false], 
        spriteImages: ['Earnest_Negotiation'] },
    { name: 'Yae Miko', imgName: 'Yae', spriteFolder: 'YaeMiko', have: [false], 
        spriteImages: ['Prayer_Time'] },
    { name: 'Clorinde', have: [false],
        spriteImages: ['Intimidating_Stance'] },

    //ANEMO
    { name: 'Chasca', have: [false], 
        spriteImages: ['Leisure_Time'] },
    { name: 'Faruzan', have: [false], 
        spriteImages: ['Casual_Conversation'] },
    { name: 'Heizou', imgName: 'Heizo', have: [false], 
        spriteImages: ['Deep_Contemplation'] },
    { name: 'Jean', imgName: 'Qin', have: [true], 
        spriteImages: ['Leisure_Time'] },
    { name: 'Kazuha', have: [true], 
        spriteImages: ['Virtuoso_Performance'] },
    { name: 'Lynette', imgName: 'Linette', have: [true], 
        spriteImages: ['Elegant_Greeting'] },
    { name: 'Venti', have: [true], 
        spriteImages: ['Spontaneous_Performance', 'Playful_Shushing'] },
    { name: 'Wanderer', have: [false], 
        spriteImages: ['Surveying_Surroundings'] },
    { name: 'Sucrose', have: [false],
        spriteImages: ['Burst_of_Inspiration'] },
    { name: 'Xiao', have: [false], 
        spriteImages: ['All_Green_and_Good_to_Go'] },
    { name: 'Xianyun', have: [false], imgName: 'Liuyun',
        spriteImages: ['Under_Control'] },
    
    //CRYO
    { name: 'Charlotte', have: [false], 
        spriteImages: ['Photographic_Muse'] },
    { name: 'Chongyun', have: [false], 
        spriteImages: ['Leisure_Time'] },
    { name: 'Diona', have: [false], 
        spriteImages: ['Leisure_Time'] },
    { name: 'Eula', have: [false], 
        spriteImages: ['Elegant_Countenance'] },
    { name: 'Freminet', have: [true], 
        spriteImages: ['Guard_Up'] },
    { name: 'Ganyu', have: [false], 
        spriteImages: ['Gentle_Countenance'] },
    { name: 'Kaeya', have: [false], 
        spriteImages: ['Leisure_Time'] },
    { name: 'Layla', have: [false], 
        spriteImages: ['Thesis_Progression'] },
    { name: 'Mika', have: [true], 
        spriteImages: ['Striving_to_Negotiate'] },
    { name: 'Wriothesley', have: [false], 
        spriteImages: ['Tidying_Up'] },
    { name: 'Qiqi', have: [false], 
        spriteImages: ['Serious_Contemplation'] },
    { name: 'Rosaria', have: [false], 
        spriteImages: ['Brandishing_Weapons'] },
    { name: 'Shenhe', have: [false], 
        spriteImages: ['Talismanic_Grace']},

    //GEO
    { name: 'Chiori', have: [false], 
        spriteImages: ['All_Green_and_Good_to_Go'] },
    { name: 'Gorou', have: [false], 
        spriteImages: ['All_Green_and_Good_to_Go'] },
    { name: 'Navia', have: [true], 
        spriteImages: ['Elegant_Countenance'] },
    { name: 'Ningguang', have: [false], 
        spriteImages: ['Refined_Countenance'] },
    { name: 'Noelle', imgName: 'Noel', have: [false], 
        spriteImages: ['Elegant_Countenance'] },
    { name: 'Yun Jin', imgName: 'Yunjin', have: [false], 
        spriteImages: ['Masters_Poise'] },
    { name: 'Zhongli', have: [true], 
        spriteImages: ['Solemn_Countenance'] },
    { name: 'Albedo', have: [false], 
        spriteImages: ['Snapshot_Essentials'] },
    { name: 'Sayu', have: [false], 
        spriteImages: ['Bleary_Eyes']},
    { name: 'Ororon', imgName:'Olorun', have: [false], 
        spriteImages: ['Little_Friend']},
    { name: 'Ayaka', have: [false], 
        spriteImages: ['Poised_to_Dance']},
    { name: 'Emilie', have: [false], 
        spriteImages: ['Fragrant_Touch']},
    { name: 'Sigewinne', have: [false], 
        spriteImages: ['Bubbles_Drifting']},
    { name: 'Shinobu', have: [false], 
        spriteImages: ['Ready_for_Battle']},
    { name: 'Citlali', have: [false], 
        spriteImages: ['Reader,_Inspired']},
    { name: 'Itto', have: [false], 
        spriteImages: ['Valiant_Hero']},
    { name: 'Varesa', have: [false], 
        spriteImages: ['Valiant_Hero'], status:'new'},
    { name: 'Lauma', have: [false], 
        spriteImages: ['Amiable_Conversation'], status:'new'},
    { name: 'Dahlia', have: [false], 
        spriteImages: ['Relaxed_Bearing'], status:'new'},
    { name: 'Chevreuse', have: [false], 
        spriteImages: ['Ready_for_Battle'], status:'new'},
        
    //{ name: '', have: [false, true], imgName:'', spriteFolder: '', spriteImages: ['', ''], status:'new', },
    
    // Current TT season is 20 || Link: https://genshin-impact.fandom.com/wiki/Thespian_Trick ...
  ],

  pathPrefix: "../assets/charaid/Genshin/",
  spritePrefix: "../assets/others/Genshin/Thespian/",

  getImgPath: (char) => {
    const imgName = char.imgName || char.name.replace(/\s+/g, ''); // fallback to name with no spaces
    return `${gameConfig.pathPrefix}UI_AvatarIcon_${imgName}.png`;
  },

  getSpritePath: (char) => {
    const folder = char.spriteFolder || char.name.replace(/\s+/g, '');
    const images = char.spriteImages || [];
    return images.map(img => `${gameConfig.spritePrefix}${folder}/${img}.webp`);
 }
};
